{% set version = "0.17.0" %}

package:
  name: pythran
  version: {{ version }}

source:
  url: https://github.com/serge-sans-paille/pythran/archive/refs/tags/{{ version }}.tar.gz
  sha256: b1f13ca239625579a92bc915bd0abae3747d96063ce55790eead2a072667fcb3

build:
  number: 0
  noarch: python
  script:
    # on windows, pythran wrongly sets %PREFIX\include instead of %PREFIX%\Library\include;
    # pythran-win32.cfg already exists and has [compiler].include_dirs; we replace it on the fly;
    # conda will detect the written environment-path and replace it as appropriate for user installs;
    # note that we need r'...' for this due to paths like D:\bld\... where python would interpret \b.
    - "python -c \"with open('pythran\\pythran-win32.cfg', 'r+') as s: a=s.read(); s.seek(0); s.write(a.replace('include_dirs=', r'include_dirs=%PREFIX%/Library/include'))\""  # [win]
    # sanity check to ensure this is set correctly
    - type pythran\pythran-win32.cfg  # [win]
    - python -m pip install . --no-deps -vv
  entry_points:
    - pythran = pythran.run:run
    - pythran-config = pythran.config:run

requirements:
  build:
  host:
    - python  {{ python_min }}
    - pip
    - setuptools
    - numpy
  run:
    - gxx                    # [linux]
    - clangxx                # [osx or win]
    - python  >={{ python_min }}
    - decorator
    - gast 0.5.*
    - ply >=3.4
    - colorlog
    - beniget 0.4.*
    - __linux                # [linux]
    - __osx                  # [osx]
    - __win                  # [win]

test:
  requires:
    - setuptools  # [py>=312]
    - python {{ python_min }}
  files:
    - dprod.py
    - simple_numexpr.py
  commands:
    - pythran -v dprod.py
    - python -c "import dprod"
    - pythran -v simple_numexpr.py -DUSE_XSIMD -march=native  # [not (ppc64le or (osx and arm64))]
    - pythran -v simple_numexpr.py -DUSE_XSIMD                # [osx and arm64]
    - pythran -v simple_numexpr.py                            # [ppc64le]
    - python -c "import simple_numexpr"
  imports:
    - omp  # [not win]
    - pythran
    - pythran.analyses
    - pythran.optimizations
    - pythran.transformations
    - pythran.types

about:
  home: http://github.com/serge-sans-paille/pythran
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a claimless python to c++ converter

  description: |
    Pythran is an ahead of time compiler for a subset of the Python language,
    with a focus on scientific computing. It takes a Python module annotated
    with a few interface description and turns it into a native Python module
    with the same interface, but (hopefully) faster.
  doc_url: https://pythran.readthedocs.io/
  dev_url: https://github.com/serge-sans-paille/pythran

extra:
  recipe-maintainers:
    - saraedum
    - serge-sans-paille
    - h-vetinari
