{% set version = "0.9.4.post0" %}

package:
  name: pythran
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pythran/pythran-{{ version }}.tar.gz
  sha256: d5d913c86cdc3a0c6387e796ec1f65c1563ca34f10201c43ae5acc757c70fd8d

build:
  number: 0
  script:
    - "{{ PYTHON }} -c 'import os, shutil; shutil.rmtree(os.path.join(\"pythran\", \"xsimd\"))'"
    - "{{ PYTHON }} -c 'with open(\"setup.cfg\", \"w\") as s: s.write(\"[build_py]\\nno_xsimd=True\")'"
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win and py27]
  entry_points:
    - pythran = pythran.run:run
    - pythran-config = pythran.config:run

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.13
    - pytest-runner
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - decorator
    - gast =0.2.2
    - networkx >=2
    - ply >=3.4
    - six
    - beniget =0.1.0
    - xsimd =7.2.2

test:
  files:
    - dprod.py
    - simple_numexpr.py
  requires:
    - {{ compiler('cxx') }}
  commands:
    - pythran dprod.py  # [not win]
    - python -c 'import dprod'  # [not win]
    - pythran simple_numexpr.py -DUSE_XSIMD -march=native  # [not win]
    - python -c 'import simple_numexpr'  # [not win]
  imports:
    - omp
    - pythran
    - pythran.analyses
    - pythran.optimizations
    - pythran.transformations
    - pythran.types

about:
  home: http://github.com/serge-sans-paille/pythran
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a claimless python to c++ converter'

  description: |
    Pythran is an ahead of time compiler for a subset of the Python language,
    with a focus on scientific computing. It takes a Python module annotated
    with a few interface description and turns it into a native Python module
    with the same interface, but (hopefully) faster.
  doc_url: https://pythran.readthedocs.io/
  dev_url: https://github.com/serge-sans-paille/pythran

extra:
  recipe-maintainers:
    - saraedum
    - serge-sans-paille
